version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${EXT_PORT}:${INT_PORT}/tcp
    networks:
      front_net:

  post:
    image: ${USERNAME}/post:${POST_VER}
    networks:
      back_net:
      front_net:
        aliases:
          - post

  comment:
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      front_net:
        aliases:
          - comment
      back_net:

volumes:
  post_db:

networks:
  back_net:
  front_net:
